services:
  - type: web
    name: MADUSHAN-MD
    env: node
    branch: main
    repo: https://github.com/madushanrathanayaka/MADUSHAN-MD.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUDO
        sync: false
